import psycopg2

# Establish a connection to the PostgreSQL database
def getConnection():
    
  conn = psycopg2.connect(
          host="localhost",
          port="5432",
          database="adv_db",
          user="postgres",
          password="1234"
      )
  return conn

connection = getConnection()
cursor = connection.cursor()

print("Creating table Variants_partition")

cursor.execute("""
  CREATE TABLE public."Variants_partition"
  (
      "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
      "PositionStart" bigint,
      "Length" integer,
      "Reference" text COLLATE pg_catalog."default",
      "Alternative" text COLLATE pg_catalog."default",
      "Type" text COLLATE pg_catalog."default",
      "GeneName" text COLLATE pg_catalog."default",
      "ClinicalSignificance" text COLLATE pg_catalog."default",
      "Disease" text COLLATE pg_catalog."default",
      "Synonimity" text COLLATE pg_catalog."default",
      "GeneRegion" text COLLATE pg_catalog."default",
      "Chromosome" integer
  ) PARTITION BY LIST ("Type");
  """)

print("Creating partitions")

type_list = ["CN", "DEL", "INDEL", "INS", "INV", "SNP"]

for type_el in type_list:
  create_table = f"""CREATE TABLE public."Variants_partition_{type_el}"
      PARTITION OF public."Variants_partition"
      FOR VALUES IN ('{type_el}')
      PARTITION BY HASH ("Chromosome");"""
  
  for i in range(0, 24):
    create_table += f"""
    CREATE TABLE public."Variants_partition_{type_el}_{i}"
      PARTITION OF public."Variants_partition_{type_el}"
      FOR VALUES WITH (MODULUS 24, REMAINDER {i});
    """
  
    print(f"Creating partition {type_el} {i}")
  cursor.execute(create_table)
  
    
cursor.execute(f"""INSERT INTO public."Variants_partition"
  SELECT * FROM public.\"Variants\";""")
connection.commit()
cursor.close()
connection.close()